# Generated by Django 6.0.6 on 2026-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='mobile',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
