# Generated by Django 6.0.6 on 2026-07-15 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_otplog_mobile'),
        ('users', '0003_coachingcenter_logo_alter_coachingcenter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='coaching_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.coachingcenter'),
        ),
    ]
