# Generated by Django 6.0.6 on 2026-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_batches_remove_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, db_column='father_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, db_column='mother_name', max_length=255, null=True),
        ),
    ]
