# Generated by Django 6.0.6 on 2026-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_father_name_student_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, db_column='school_name', max_length=255, null=True),
        ),
    ]
